### ISSUE TITLE
Shelter enhancements re: NCR EM and Mass Care feedback

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#10]
Add in the following fields:

- If the shelter allows pets, capacity for animals (two separate fields, one for companion animals, another for large animals)

- New icon/halo/visual to show spontaneous or non-jurisdictional sponsored shelters (purple?)

**Comment by epratt5** [comment]
Make the Public Map & Dashboard public for the Aug 17 exercise.

**Comment by epratt5** [comment]
Had to make the main web map public, so I need to be sure to minimize access post exercise.

**Comment by epratt5** [comment]
Hidden question in the shelter survey available for animal capacity.
Hidden symbol in the web map to show spontaneous or non-jurisdictional shelters.
Both ready to go, but not published.

**Comment by kkay82** [comment]
Proposed animal fix/dropdown:
**Allows Animals**

1. Yes - Companion animals only
2. Yes - Large animals only
3. Yes - Companion and large animals
4. No

Spontaneous shelter visual/icon choices:

1. Use the same icon as a shelter, make it purple.
2. Use the same icon as a shelter (green), and ring it with a purple halo

**Comment by epratt5** [comment]
I've got the Spontaneous shelter symbol working. The Edit Shelters tab doesn't refresh quickly, so I'll try to fix that. How do we want to do the legend?

**Comment by epratt5** [comment]
I got the spontaneous symbol to refresh now.

**Comment by kkay82** [comment]
I get this error. The symbol shows green:
![image](https://user-images.githubusercontent.com/67169954/93477623-7c38f580-f8b8-11ea-92a3-18e20a5caf54.png)

**Comment by epratt5** [comment]
I tried it out with my NAPSG account and it took longer than it should have to show the purple ring, but it did show up under a minute of waiting. I'll try to get that to sync faster.

![image](https://user-images.githubusercontent.com/31831585/93651818-dc2abb80-f9e0-11ea-905e-c2f91ac0fb39.png)

**Comment by epratt5** [comment]
This is what the legend currently looks like:
![image](https://user-images.githubusercontent.com/31831585/93652156-029d2680-f9e2-11ea-9c30-66e347045d51.png)

**Comment by epratt5** [comment]
I also noticed that in the Recently Updated List in the dashboard, the purple circle doesn't show because the list isn't capable of coding from two separate layers.

**Comment by kkay82** [comment]
K, tested again. The purple ring shows up pretty quickly on the dashboard, and like 30 seconds on the edit shelters. I think that is good. As far as the recently updated list, it doesn't necessarily have to show the purple ring, but it should show that a shelter was opened.

**Comment by epratt5** [comment]
I don't know why that isn't working. I'll try to figure it out. As far as I know, that should happen automatically just like the other status changes.

**Comment by epratt5** [comment]
For some reason, I think if you don't change anything other than the status, it doesn't move the shelter up in the recently updated list. It just changes the icon and keeps the shelter in the last position.

**Comment by epratt5** [comment]
Somehow, this VERY important little checkbox was deselected. This little box controls the update list widget.
![image](https://user-images.githubusercontent.com/31831585/94086631-8dfb2b00-fdd9-11ea-9bca-e2ffd9c4ab33.png)

**Comment by epratt5** [comment]
This little box is in the Settings tab on the item details page of the main feature layer. 51440

**Comment by kkay82** [comment]
Minor configuration issue. May not be possible to fix, but when you open a spontaneous shelter and choose that filter in the dashboard, it works:

![image](https://user-images.githubusercontent.com/67169954/96501547-bb3acd80-120d-11eb-9733-a144675b4237.png)

However, if you select open shelters from the filter, it removes the icon and leaves the purple circle.

![image](https://user-images.githubusercontent.com/67169954/96501603-cdb50700-120d-11eb-96ac-3fa06560d1d0.png)

**Comment by epratt5** [comment]
I had to add another filter when I created that symbol. Thanks for catching this. It's now fixed.
