### ISSUE TITLE
Shelter caches/supplies

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#11]
The region has some supply caches/trailers with sheltering equipment. Think cots, blankets, walkers, stuff for AFN, etc. These are pretty static and can be added in like a shelter, but the fields are very different. Things to consider:

- Consumable vs non-consumable items
- If trailer, type of trailer and hitch required
- Actual supply list
- Last time inventoried
- Grant funded vs. agency owned equipment

Not sure if it makes sense to make another app kind of like the public facing map to show caches within X buffer, just a thought.

**Comment by epratt5** [comment]
I created a feature layer without data to show the locations of shelter supply caches. [https://ncr.maps.arcgis.com/home/item.html?id=7b0ee04924f940138cc49c839db2f3b3#overview](url)
There is no data in the feature layer.
The feature layer has been added to the main shelters web map, but it is turned off.

**Comment by kkay82** [comment]
Lets add in a shelter cache symbol - maybe use this as a placeholder for now. Lets make it a symbol you can place in the smart editor, and have the following fields:

1. Cache owner
2. Cache funded by dropdown with:

  - Grant funded

  - Agency funded
3. Type of cache dropdown with:

- Loose supplies

- Trailer (driveable)

- Trailer (towable)

Then lets just point to the excel spreadsheet for the current inventory.

 
![INCDNT_COMAND_WHITE-_SOLID-Supply-Distribution_Food_Water_256x256](https://user-images.githubusercontent.com/67169954/92655821-345e1100-f2af-11ea-8ce5-e3efe2982ba1.png)
