### ISSUE TITLE
Find best available hotel / lodging layer and as a reference layer in the web map

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/NAPSG-Shelter-System#12]
Discussed on 8/18 - identify which layer is the best for NCR (OSM, Safegraph, etc)

**Comment by kkay82** [comment]
Tabled until meeting /w Mass Care

**Comment by kkay82** [comment]
Is there a way to change the icon of a shelter when you select a facility type? If so, can we add hotel/motel to facility type?

**Comment by epratt5** [comment]
I don't remember: Was I supposed to make a separate feature layer for the hotels or just add it to the facility type? I did the latter.

**Comment by kkay82** [comment]
The way you have it is great. People can just identify it is a hotel/motel. I wish the form had logic behind it...or does it? For example, if we select "hotel/motel" can it then show the field for "accepts vouchers"?

**Comment by epratt5** [comment]
I can put that in the survey form, but I'm not sure how to show that on the icon, if that's what you want.

**Comment by kkay82** [comment]
Disregard vouchers. We will make it a part of the training if people open a hotel as a shelter, they should put that information in either the public message or other information part.
