### ISSUE TITLE
Widget configuration on the dashboard

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#13]
Recently updated shelter list:

- How many lines can we display? Seems like it only shows the last 25

- Can we add any other language when something updates in there? Pretty intuitive if it shows a green icon it means a shelter has been open, but can we add text?

**Comment by epratt5** [comment]
Yes, I can change the number of edits displayed. It is currently only set to 25.
I can add more information to the list, but I would have to translate it myself. AGOL doesn't have a translator widget/tool. I would assume the page would be translated based on the web browser settings of the user, but that isn't a guarantee.

**Comment by kkay82** [comment]
Will leave at 25 lines for now.

Emilie will look into text for update widget
