### ISSUE TITLE
Helper text and website links on public map

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#14]
Remove the "if available" helper text that shows up on the public map when putting in a public message or website.

The website links are also broken.

**Comment by epratt5** [comment]
Note to self: try to put hint text in the shelter editor app and remove it from the public map popup

**Comment by epratt5** [comment]
I removed the "if available" text from the popup. I don't see a way to make it a hint text in the apps.
There are several people who don't seem to be adding the website links correctly, if at all. Denver has done a good job, their links work and open a new tab to their page. Right now we have the filler text "More Info" where people are supposed to supply their own weblinks. It will show as static, non-clickable words if they don't input a link. It's basically a hint text.

**Comment by kkay82** [comment]
Helper text TBD.

Website requires http:// , may put in starter.

**Comment by epratt5** [comment]
I managed to get some Hint Texts for the items that will show up in the Public Map, but the mouse has to hover over the attribute to show the text.

**Comment by epratt5** [comment]
No known way to make the Public fields bold or to add a note above the fields.
