### ISSUE TITLE
Multi-county jurisdictions

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#15]
Some jurisdictions are in multiple counties (Aurora, Littleton, Westminster). There isn't a way to filter by jurisdiction or multiple counties. Not sure which solution is best:

1. Allow the user to select multiple counties from the dashboard to filter by
2. Have a drop down of select jurisdictions.

**Comment by epratt5** [comment]
Easier to do option 1 than option 2. I would need to know the jurisdiction names or designations to create a drop down.

**Comment by kkay82** [comment]
I think if we can just allow people to filter by multiple counties then those that fall into that category will know to do it. Like holding ctrl and selecting multiple.

**Comment by kkay82** [comment]
Will go with option 1.

**Comment by epratt5** [comment]
Done
