### ISSUE TITLE
Shelter shows up in wrong location

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#16]
Deer Trail Grace Baptist Church shows up in the middle of Denver (incorrect). The address is correct. Leads to a question:

- If a shelter is in the wrong location, do users have to delete/re-add?

**Comment by epratt5** [comment]
![image](https://user-images.githubusercontent.com/31831585/90707160-f6983a80-e264-11ea-8ec7-41e485a548f3.png)
Is this not the right location? Google Maps on the right.

**Comment by epratt5** [comment]
I would assume it would be easiest to delete and then re-add a shelter if it shows up in the wrong place. It shouldn't be a problem to fix one or two. If a bunch start showing up in the wrong place, then we'll have a big bug on our hands.

**Comment by kkay82** [comment]
Gary from Denver moved the shelter to the correct location. He used the lat/long tool in "edit geometry" at the end of the field list. Confused why it geocoded it wrong, maybe we can check the spreadsheet.

**Comment by kkay82** [comment]
Ensure that users know about edit geometry option.
