### ISSUE TITLE
Public map filters

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#17]
Can the public map allow filterable search? For example:

- Find nearest **warming shelter**

- Find nearest **overnight shelter**

**Comment by epratt5** [comment]
Done. I'll leave this open if any more filter requests come in.

**Comment by kkay82** [comment]
Tabled for larger conversation about terminology/symbology

**Comment by epratt5** [comment]
I managed to create a filter on the Near Me widget! Woo!
