### ISSUE TITLE
Refreshing pages to show updated information

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#18]
The dashboard tab only shows updated information (such as a new shelter opened/closed) if you change the extent or refresh the page. The public map only shows updated information when you refresh the page. Can we change this to automatically refresh?

**Comment by epratt5** [comment]
The Public Map is set to refresh every half minute for non-static layers. I don't know about the dashboard. I'll look into this further.

**Comment by epratt5** [comment]
https://doc.arcgis.com/en/arcgis-online/create-maps/set-refresh-interval.htm
The map has to be refreshed at the feature layer level.

**Comment by epratt5** [comment]
[https://community.esri.com/thread/209399-ops-dashboard-web-version-table-refresh]
From what I can tell, the tables and other widgets in the Dashboard can't be refreshed automatically because they're not created with the web map, but the Esri team is working on this solution.

**Comment by epratt5** [comment]
I  need to make sure to set the cache interval on the web map back end.

**Comment by kkay82** [comment]
Double checking on this one to make sure we don't break stuff (re: Paul on SAR top layer list)

**Comment by kkay82** [comment]
Emilie to review checklist and then close issue.

**Comment by epratt5** [comment]
To protect the cache, we have to turn off editing options, sync, and ownership-based access when editor tracking is enabled. I'll make a note of this in the GIS page.
