### ISSUE TITLE
Dashboard Status Selector loses an option

### ISSUE THREAD

**Issue by epratt5** [afackler/NAPSG-Shelter-System#21]
When there aren't any shelters with one of the Status options, that option doesn't show in the selector bar. Right now, at the end of the August exercise, showing Open shelters isn't an option because there aren't any. If a shelter were opened, that would become an option. I don't know if this is a bug or an enhancement issue. I'll try to see if I can stabilize the selector bar so it is consistent.

![image](https://user-images.githubusercontent.com/31831585/90946698-5295c700-e3fd-11ea-86b0-f4d31ccc2ba6.png)

**Comment by kkay82** [comment]
I like it the way it works right now. Keeps it cleaner and prevents people from thinking there are open/closed ones. Just my opinion.
