### ISSUE TITLE
Add new field (A) Facility Purpose

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#22]
We don't identify anywhere in the tool if it is an evacuation center, warming center, overnight shelter, etc. Lets add that underneath Facility Type and have the below options:

- Evacuation Center
- Warming Center
- Short-term shelter
- Long-term shelter

We can add definitions in the technical user guide. I can work on that.

**Comment by epratt5** [comment]
Under Occupancy Duration we have:

- Short-Term / Evacuation

- Long-Term / Overnight

- Other

**Comment by kkay82** [comment]
Okay. The ones there don't make much sense, I assume it came from the crosswalk of the regional shelters. Duration isn't the best term, and occupancy type also doesn't make much sense. Lets remove both of those fields, and replace with the facility purpose. Having days/hours of operations satisfies the duration. Lets implement the facility purpose and also add "other" as an option. Feel free to tell me I am way off base or if the mass care committee was adamant on this item.

![image](https://user-images.githubusercontent.com/67169954/92831542-c3dcf000-f393-11ea-9a78-3c19d0b0b831.png)

**Comment by epratt5** [comment]
The Occupancy Type was to cover the various animal needs. Most importantly if the animals have to be sent somewhere else, but I think I covered that in the note about Animals, so it should be fine to delete it.

**Comment by kkay82** [comment]
Lets sync on this one at some point, I think I was confusing us all!

**Comment by epratt5** [comment]
Oh I misread it. I didn't completely read that you wanted a new field. Yes, let's sync. Thanks.

**Comment by epratt5** [comment]
I created the Facility Purpose field, but I need to update the field descriptions before the documentation/glossary is finished and this task is closed.

**Comment by kkay82** [comment]
Okay, I went through the current fields in the tool and the order and updated the documentation accordingly. Need you to reorder it to match it. Only things out of order are the animal capacities at the end.
![image](https://user-images.githubusercontent.com/67169954/93220621-02730180-f72a-11ea-8a5d-7a04e914178f.png)

**Comment by epratt5** [comment]
I made a decision: We only have a handful of Active Incident fields, so I moved them all up to the top. Except for the animal capacity fields. Those remain below the main Allows Pets/Animals field.

**Comment by kkay82** [comment]
I like it, nice work. Only issue I see now is the actual popups of the shelters don't reflect the new ordering.

**Comment by epratt5** [comment]
Good catch. Thanks.
