### ISSUE TITLE
Shelter cache symbol doesn't show up

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#24]
When adding a new shelter supply cache from the smart editor, the icon does not show up. I tried adding two test caches so they may be somewhere hidden in the background.

- Make sure the cache symbol shows up in both the edit shelters and dashboard

- Make sure you remove my two test cachec

**Comment by epratt5** [comment]
I noticed this problem this week too. Thanks for bringing it to my attention here.

**Comment by epratt5** [comment]
I'm struggling with this issue. If I pull the layer into a desktop app (ArcGIS Pro or ArcMap), the geometry shows, but not in the apps online.

**Comment by epratt5** [comment]
I finally got this to work. I had to do some footwork in ArcGIS Pro and basically recreate it as an item online, but there isn't any data, so it didn't mess anything up.
