### ISSUE TITLE
Add cache count to preparedness indicators widgets

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#26]
Just like total shelters, add the total cache count. If possible, add it as a tab option with the total shelters widget. I want to test it out and get some feedback from folks if they like it that way.

![image](https://user-images.githubusercontent.com/67169954/95921741-146ab300-0d6f-11eb-8a48-2cbbb7da9752.png)

**Comment by epratt5** [comment]
I also like this symbol for caches. Do you prefer this or the trailer icon?
![image](https://user-images.githubusercontent.com/31831585/95929107-278e7a80-0d91-11eb-900b-2d10122f8654.png)

**Comment by kkay82** [comment]
I agree, keep this new icon.

**Comment by kkay82** [comment]
I like the way it looks, nice work!
