### ISSUE TITLE
Additional fields to shelter caches

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#27]
Add a notes field

I also have a question around the supply list field. You have helper text to provide a spreadsheet or pdf, but I don't see how they can do that.

**Comment by kkay82** [comment]
I see the attachment button now. Still would like a **notes field** for anything extra people want to put.

**Comment by epratt5** [comment]
I changed the Supply List field back to a comments field with helper text instructing the user to attach the list at the bottom.

**Comment by kkay82** [comment]
Looks good. I attached an excel spreadsheet to test. It uploads just fine but doesn't display.

**Comment by epratt5** [comment]
From what I've been able to find, the spreadsheet or PDF will have to be downloaded or opened in a new tab to display the attachment. It won't open in the app itself. I don't think that would be a problem, I think most people would be fine with it as a downloadable option.

**Comment by epratt5** [comment]
I don't know why the attachment won't show or allow the user to download from the Experience Builder. It works fine in the Shelter Editor app by itself. For the Dashboard, I would have to create a "Details" [widget](https://doc.arcgis.com/en/dashboards/get-started/details.htm) to be able to display the attachment. I'll keep looking into this, but this is what I have for now.

**Comment by epratt5** [comment]
I think this issue might have to do with the EB update, coming 10/19-10/20.

**Comment by kkay82** [comment]
Sounds good. I can still make a video just showing they can attach the spreadsheet, not necessarily opening it.

**Comment by epratt5** [comment]
Attachments still not opening from EB. I'll continue to look into this.

Edit: It allows me to download the spreadsheet if I refresh the window that opens when the attachment link is clicked.

**Comment by kkay82** [comment]
Interesting. At least it works, but that is not ideal at all.

**Comment by epratt5** [comment]
The new window still needs to be refreshed to download the attachment. I don't know how to get around this.

**Comment by epratt5** [comment]
Charlotte is going to poke around the HTML a little for this to see if she can find the issue.

**Comment by epratt5** [comment]
Image files work well and show up in the pop-up itself. Documents and spreadsheets need to be downloaded after the new window is refreshed. I can't find a way around this.

**Comment by kkay82** [comment]
Push to ESRI support. Doesn't make sense the way it works, no one would think to refresh the page to get it to download.

**Comment by epratt5** [comment]
Support ticket submitted. Hopefully it won't take long to diagnose.

**Comment by epratt5** [comment]
Support ticket was not created by Shubhan on Friday 11/20/2020. Esri support is currently working with me to get this resolved 11/24/2020.
Esri meeting ID: 3483774547

**Comment by epratt5** [comment]
Rohan Jagtap helped me today, 11/24/2020. ESRI Case # 02687934
The attachment issue is tied to both Experience Builder and the Dashboard. Individual applications, including the Dashboard by itself, work normally.

**Comment by kkay82** [comment]
> Rohan Jagtap helped me today, 11/24/2020. ESRI Case # 02687934
> The attachment issue is tied to both Experience Builder and the Dashboard. Individual applications, including the Dashboard by itself, work normally.

Forgot if I asked you about the follow-up to this. Has this been reported as a bug? Is it on our end?

**Comment by epratt5** [comment]
Still no word. I just sent a follow-up email.

**Comment by epratt5** [comment]
This has been logged as a bug, but has since been fixed!

**Comment by kkay82** [comment]
Doesn't work for me, tested with excel file. Still had to refresh the page.

**Comment by epratt5** [comment]
I tested this again in my personal account, with my Experience Builder, and it's still an issue. 12/7/20.

**Comment by epratt5** [comment]
I'm going to close this issue here because it has been logged by ESRI.
Officially logged with ESRI:
Bug Number: BUG-000136012
Synopsis: "Feature Attachments fail to download when accessed through a Dashboard embedded in Experience Builder."

**Comment by kkay82** [comment]
@epratt5 Sounds good, Lets make sure we have a process if they respond to the bug and fix it. Can Jared see your bug reports as AGOL administrator? Don't want you having to log in to check.

**Comment by epratt5** [comment]
@kkay82 Yes, Jared should be able to see the bug reports.

**Comment by kkay82** [comment]
@epratt5 Sounds good, thanks. I guess anyone with admin access on AGOL can view bug status.
