### ISSUE TITLE
Share options and custom share options are broken

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#34]
When using the "share" widget, the link to share to the app is broken. It just constantly redirects, and does the same when using the custom share options.

![image](https://user-images.githubusercontent.com/67169954/99579589-9c119600-299b-11eb-8218-057f9fb5fc7d.png)

**Comment by epratt5** [comment]
I wonder if this is another bug from the EB update. I'll check into it.

**Comment by epratt5** [comment]
It seems to be working for me. It opens the Shelter Editor by itself, not the whole EB, but it works.

**Comment by kkay82** [comment]
Works for me this morning too.
