### ISSUE TITLE
Add second cache icon for animal supply cache

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#35]
If it is easy to add a second icon for animal supply caches lets do it. If not, lets at least add that as an option in the drop-downs.

**Comment by epratt5** [comment]
Everything is set up for Human cache only. I'm not sure where I would add the dropdown option. I could add a new field to symbolize between human & animal, but I need some direction on what to call it. We already have "Type of Cache" for loose supplies vs. trailer. [https://ncr.maps.arcgis.com/home/item.html?id=337ed9ca9f7b47a1874dc0b1be8872c5&view=table&sortOrder=desc&sortField=defaultFSOrder#data](url)

**Comment by epratt5** [comment]
Clarification: It's simple, I just need more direction.

**Comment by kkay82** [comment]
My initial thought is to create a separate animal cache symbol and copy over all of the fields from the human cache. That way people can differentiate the types of caches on screen.
