### ISSUE TITLE
Training Videos taking up space

### ISSUE THREAD

**Issue by epratt5** [afackler/NAPSG-Shelter-System#36]
Is it possible to have the training videos stacked so they don't take up as much room?
This will eventually need its own tab in the menu bar as more videos are made. Maybe the video tab could just point to a YouTube playlist?

**Comment by epratt5** [comment]
Maybe make a button that redirects to YouTube, like the Tech Guide button.

**Comment by epratt5** [comment]
I think we should make a YouTube playlist for the videos that can be embedded in the Experience Builder with a button. This would be especially helpful for the mobile version.
@kkay82

**Comment by kkay82** [comment]
Playlist link: https://www.youtube.com/playlist?list=PLtl2mJ4_4VyDBVwhnhGTxgZ0PZ_gx6_0B
