### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by epratt5** [afackler/NAPSG-Shelter-System#37]
I've worked on the tablet/mobile view of the Experience Builder. Please review.

**Comment by kkay82** [comment]
On the tablet view:

- Remove training video and advanced training video, replace with button to the new youtube playlist: https://www.youtube.com/playlist?list=PLtl2mJ4_4VyDBVwhnhGTxgZ0PZ_gx6_0B

- Include the QR code somewhere, preferably up top.

On the mobile view:

- Reorder the buttons to match the other options (edit -> dashboard -> public map -> new shelter).

- Include QR code somewhere, preferably up top.

- Remove training video and advanced training video, replace with button to the new youtube playlist: https://www.youtube.com/playlist?list=PLtl2mJ4_4VyDBVwhnhGTxgZ0PZ_gx6_0B . The button can be "Training Video Playlist"

**Comment by epratt5** [comment]
I moved things around and did what you requested above. If all looks well, go ahead and close this issue.

**Comment by kkay82** [comment]
Looks great. I will close this for now but still want to do more testing on my end using mobile devices. Minus looking at the mobile view on EXB editor, I haven't really messed around with it on my phone yet.
