### ISSUE TITLE
Use www.arcgis.com link for Shelter Editor

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/NAPSG-Shelter-System#4]
I *think* if we use the ncr.maps.arcgis.com URL it is going to give users an issue when they try to login with their own account outside NCR, even if they have access via a group. At least until Esri makes updates in September (I hope). 

Change the URL for this embed to www.arcgis.com and it should be OK. 

Maybe the same for Survey123, Dashboard, etc

![image](https://user-images.githubusercontent.com/4256979/85780963-0ae30f80-b6da-11ea-9ed8-f6d1cc2f3b8d.png)

**Comment by epratt5** [comment]
The viewer still has to select 'OK' to login to AGOL when trying to open the apps, but as long as you're logged in with an account that has permission to view the apps, it will just acknowledge that you are logged in and you don't have to actually enter your credentials.
