### ISSUE TITLE
Widgets in the dashboard issues

### ISSUE THREAD

**Issue by kkay82** [afackler/NAPSG-Shelter-System#6]
Very weird widget updates with the generators, allows pets, and ADA access when you filter by county and zoom in/out. Can demo it for you if needed, but seems like it filters the shelters by county, but is still calculating the % in the widgets by the entire map extent.

**Comment by epratt5** [comment]
I fixed the Recently Updated list by correcting the data sort to be done by Edit Date.
It seems like the indicators lag when the selection changes. I'll look closer tomorrow. I can't quite figure it out now. As far as I can tell, they work fine. The percentages seem to match up and everything looks good, but it doesn't always update with the selection/zoom.

**Comment by epratt5** [comment]
I think this can be resolved by simply having the County Selector zoom on the map, but I can't find the zoom option that coordinates the selector to the map.

**Comment by epratt5** [comment]
I think I fixed it. I hadn't connected the County Selector to reflect changes in the Pets and ADA indicators. I'd still like the map to zoom to the county when the selection changes, but I don't think that's a big issue right now. I'll make it an enhancement item.

**Comment by kkay82** [comment]
It all works, nice work!
