### ISSUE TITLE
Public Message - Smart Editor

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/NAPSG-Shelter-System#8]
We should make the field in Smart Editor "Rich Text" or multi-line so that the person editing has more space for their message.

I'll try adding a screenshot later if this is unclear. 

You may want to check a few others and see where it makes sense to apply this setting.

**Comment by epratt5** [comment]
Updated in the web app by configuring the attribute in the popup. Let me know if any other fields should be multiline.

**Comment by epratt5** [comment]
I updated the message fields and "other" fields. Maybe Contact Name or Address?
