### ISSUE TITLE
Occupancy Duration

### ISSUE THREAD

**Issue by pjdohertygis** [afackler/NAPSG-Shelter-System#9]
I think this list needs a little clean-up? 

Long-Term / Evacuation does not make sense. I think we mean Short-Term / Evacuation. 
To me, long-term would indicate there are beds. 

![image](https://user-images.githubusercontent.com/4256979/87968731-b67f4580-ca75-11ea-87ee-e48b5d42bc57.png)

Do we remember where these dropdowns came from?

**Comment by kkay82** [comment]
Use these:

Evacuation
Short-Term
Long-Term
Warming Shelter
Overnight

**Comment by epratt5** [comment]
Should I update the survey as well?

![image](https://user-images.githubusercontent.com/31831585/87969762-bd678180-ca90-11ea-9815-ee7a31a9e3be.png)

**Comment by kkay82** [comment]
Yes please.

**Comment by epratt5** [comment]
Just a styling question: Which is better: Drop-down menu or Buttons in the survey?

**Comment by kkay82** [comment]
Buttons for survey.
